# This file describes an application. You can have multiple applications
# in the same project.
#
# See https://docs.platform.sh/user_guide/reference/platform-app-yaml.html

# The name of this app. Must be unique within a project.
name: app

# The runtime the application uses.
type: php:8

# The relationships of the application with services or other applications.
#
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
    database: "db:mysql"
    redis: "cache:redis"

build:
    flavor: none

# Add additional PHP extensions.
runtime:
    extensions:
        - iconv
        - dom
        - simplexml
        - exif
        - opcache
        - imagick
        - fileinfo
        - pdo_mysql
        - gd
        - mbstring
        - zlib
        - zip
        - intl
        - curl

variables:
    php:
        memory_limit: 512M

# The 'mounts' describe writable, persistent filesystem mounts in the application.
mounts:
    "/var":
        source: "local"
        source_path: "var"
    "/src":
        source: "local"
        source_path: "src"
    "/templates":
        source: "local"
        source_path: "templates"
    "/translations":
        source: "local"
        source_path: "translations"
    "/public/bundles":
        source: "local"
        source_path: "web_bundles"
    "/config/local":
        source: "local"
        source_path: "config_local"

# The configuration of app when it is exposed to the web.
web:
    locations:
        "/":
            root: public
            passthru: "/index.php"
            allow: true
            rules:
                "^/videos/(?<resource>.*)$":
                    allow: true
                "^/img/(?<resource>.*)$":
                    allow: true
                "^/static/(?<resource>.*)$":
                    allow: true
                '^/cache-buster-(?:\d+)/(.*)':
                    passthru: "/$1"
                '^(?!/admin)(.+?)\.((?:css|js)(?:\.map)?|jpe?g|gif|png|svgz?|eps|exe|gz|zip|mp\d|ogg|ogv|webm|pdf|docx?|xlsx?|pptx?)$':
                    passthru: "/var/assets$uri"
        "/var/assets":
            root: public/var/assets
            passthru: false
            scripts: false
            allow: true
            rules:
                \.((?:css|js)(?:\.map)?|jpe?g|gif|png|svgz?|eps|exe|gz|zip|mp\d|ogg|ogv|webm|pdf|docx?|xlsx?|pptx?)$:
                    expires: 2w

# The size of the persistent disk of the application (in MB).
disk: 2048

# The hooks executed at various points in the lifecycle of the application.
hooks:
    build: |
        set -e
        bash install-redis.sh 5.1.1
        # This is needed for the installer in the deploy hook.
        curl -sS https://platform.sh/cli/installer | php
        wkhtmltopdf -V
        composer install --no-ansi --no-progress --prefer-dist --no-scripts
    deploy: |
        if [ ! -f var/.platform.installed ]; then
            platform sql "ALTER DATABASE CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
            # These values are for the inital setup only.  You really need to change them
            # after the site is installed.
            export PIMCORE_INSTALL_ADMIN_USERNAME='admin'
            export PIMCORE_INSTALL_ADMIN_PASSWORD='admin'
            ./vendor/bin/pimcore-install --no-interaction --ignore-existing-config --no-debug
            touch var/.platform.installed
        fi
        # Clear env cached
        ./bin/console cache:clear
# The configuration of scheduled execution.
crons:
    pimcore_cron:
        spec: "*/5 * * * *"
        cmd: "bin/console maintenance"
