# Default configuration for "SimpleRESTAdapterBundle"
simple_rest_adapter:
    # Prefix for index names.
    index_name_prefix: datahub_restindex

    # List of Elasticsearch hosts.
    es_hosts:
        # Default:
        - localhost

    # Global Elasticsearch index settings.
    index_settings:
        # Defaults:
        number_of_shards: 5
        number_of_replicas: 0
        max_ngram_diff: 20
        analysis:
            analyzer:
                datahub_ngram_analyzer:
                    type: custom
                    tokenizer: datahub_ngram_tokenizer
                    filter:
                        - lowercase
                datahub_whitespace_analyzer:
                    type: custom
                    tokenizer: datahub_whitespace_tokenizer
                    filter:
                        - lowercase
            normalizer:
                lowercase:
                    type: custom
                    filter:
                        - lowercase
            tokenizer:
                datahub_ngram_tokenizer:
                    type: nGram
                    min_gram: 2
                    max_gram: 20
                    token_chars:
                        - letter
                        - digit
                datahub_whitespace_tokenizer:
                    type: whitespace
